version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: evil_corp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable'
